### ISSUE TITLE
您好，你们这个方法咋用啊，没有示例啊

### ISSUE THREAD

**Issue by markme123** [ZhaiLab-SUSTech/snuupy#2]
你好，我们团队也正在进行ONT  单细胞研究，对你们团队的方法很感兴趣，希望能提供示例。你们这套最终数据有效率是多少啊

**Comment by liuzj039** [comment]
抱歉回复晚了。
你可以clone这个项目之后直接更改snakemake文件夹里的config文件，然后运行对应的snakefile就可以了。
