### ISSUE TITLE
Required files to run snuupy

### ISSUE THREAD

**Issue by nurong2** [ZhaiLab-SUSTech/snuupy#4]
Hi,

I am attempting to analyze the root FlsnRNA-seq data published along with snuupy in Genome Biology (https://doi.org/10.1186/s13059-021-02288-0). I have downloaded the raw data from NCBI (PRJNA664874), which is given in fastq format. However, the pipeline seems to require the fast5 and nanoporeSeqSummary files, which are unavailable. 

Is it impossible to run this pipeline with only fastq files or is there something that I have not understood? I would love to be able to analyze this data.

Thanks,
Soon Hyung Bae

**Comment by liuzj039** [comment]
I apologize for the delayed response. It appears that there was an oversight during the submiting process to the NCBI database. I will make sure to re-upload the data promptly to rectify this issue. I sincerely hope that this oversight has not caused any inconvenience for you.

**Comment by liuzj039** [comment]
Hi, @nurong2. I have just uploaded the Fast5 file to the [OMIX database](https://ngdc.cncb.ac.cn/omix/release/OMIX005139), and it will be released tomorrow. This is the raw Fast5 file, so you can use Guppy to re-Basecalling and obtain the Summary file. I apologize once again for any inconvenience caused.
